In [42]:
import os
import sys
import numpy as np
from scipy.spatial.qhull import Delaunay
import networkx as nx

path = "/Users/kfraga/Box Sync/SUMMER-PROJECTS-ANISH-2019/protein-clique-analysis/residue_cliquing_project/membrane_pdbs/"
os.chdir(path)

In [43]:
s="106.4     "
news = np.float64(s)
print(news)
type(news)

106.4


numpy.float64

In [44]:
coords = []
atomtores = dict()
restoatom = dict()
resindex = 0
with open("4quv.pdb",'r') as pdb_file:
    for line in pdb_file:
        if line[0:4] == "ATOM":
            atomnum = int(line[6:11].strip(" "))
            residuenum = int(line[22:26].strip(" "))
            atomtores[atomnum] = residuenum
            restoatom[residuenum] = atomnum
            coords.append([np.float64(line[30:38].strip(" ")),\
                               np.float64(line[38:46].strip(" ")),\
                               np.float64(line[46:54].strip(" "))])
#print(coords)
coords = np.array(coords).reshape((atomnum,3))
print(coords)

[[ 23.968  12.972 -10.092]
 [ 24.031  14.032  -9.095]
 [ 22.796  14.004  -8.177]
 ...
 [ -2.99   22.542 -13.044]
 [ -2.948  21.157 -13.052]
 [ -1.857  20.507 -13.581]]


In [54]:
tri = Delaunay(coords)
len(tri.simplices)

21688

In [34]:
def readpdb(fileobj=None, filepath=None):
    if fileobj is None and filepath is None:
        raise SyntaxError("Need to give file object or path to pdb file")
    elif fileobj:
        print("woking on object")
    elif filepath:
        print("reading from file")
        fileobj = open(filepath, 'r')
    
    # only work on file object

In [35]:
readpdb(filepath="4quv.pdb")

reading from file
